### ISSUE TITLE
Add instructions about how to use our CSS

### ISSUE THREAD

**Issue by jessicard** [hackclub/css#10]
Right now, it's hard to know where to jump in. it would be nice if there were discrete instructions on how to use this CSS. As a start, maybe something in the README like:

## How to get started

1. Create a new folder for your site
1. Add a `theme.css` file inside your folder
1. Copy the `theme.css` (link to the raw maybe?) into your `theme.css`
1. Add a `style.css` file inside your folder
1. Add an `index.html` page inside your folder
1. Link to your CSS files in the `<head>` tag (maybe link to some docs about how that tag looks)
1. View https://theme.hackclub.com/ for a visual representation of our theme
1. View https://github.com/hackclub/css#hack-club-css for the documentation of the tags in our theme
1. Run your static site locally with `python -m SimpleHTTPServer` and view it at `http://localhost:8000/`
1. Have fun and get creative making websites!

**Comment by jessicard** [comment]
I put together a static theme template that includes the CSS from this. What do you think, is this useful @sampoder? 🤔 https://github.com/hackclub/static-site-template

That repo also points to another example I was playing with for using our theme on a static site, https://github.com/hackclub/contribute

**Comment by sampoder** [comment]
that would be super helpful! could we call it `css-starter`?

**Comment by jessicard** [comment]
@sampoder def down with renaming it! i like the name `css-starter`, my only slight concern is that people may pass over it and not realize it's a website skeleton ready to go. what do you think? 

with that being said, i don't love the current name either. is `website-starter` too generic?

**Comment by sampoder** [comment]
css-starter would be inline with theme-starter, i think if coupled with a
good description it would do the job

**Comment by jessicard** [comment]
@sampoder I'm sold!

**Comment by jessicard** [comment]
For posterity, @sampoder fixed that in https://github.com/hackclub/css/commit/6dce6cd033ec498a20fd5dbac6dfbce5961449df
