### ISSUE TITLE
Run server from root

### ISSUE THREAD

**Issue by jessicard** [hackclub/css#13]
If I was to run this in the future, and I wasn't reading the README, I'd forget that I have to go into `/docs` to run the server I think. What do you think about moving that into the root directory?

**Comment by sampoder** [comment]
The current docs setup limits this from being possible, as it would overwhelm the root directory with boilerplate files. However if that setup was to change this would be preferred.

**Comment by jessicard** [comment]
Makes sense from the context in https://github.com/hackclub/css/issues/14! Feel free to close :)

**Comment by sampoder** [comment]
this can also now be done!
