### ISSUE TITLE
Make this into a static site

### ISSUE THREAD

**Issue by jessicard** [hackclub/css#14]
It would be nice if people could view this project as a simple static server instead of having to have `npm` going, which raises the barrier to entry. I figure if people are looking at this raw CSS repo, they're maybe wanting a static site. Otherwise I figure they'd be looking at https://github.com/hackclub/theme maybe. What do you think? Is there a benefit here for this repo being a JS app?

The alternative could be that it's a simple to run static site that you run with `python -m SimpleHTTPServer`, and no external dependencies would be needed. Would love peoples thoughts on this!

**Comment by sampoder** [comment]
The docs site is wrapped in Next.js, as it enables us to use environmental variables in our redirects configuration file. These redirects are important to have in production. I will explore a psuedosolution to this through symlink-ing.

For now, I'm removing the good first issue tag from this and assigning myself as this is a larger issue with the repo.

**Comment by jessicard** [comment]
@sampoder Ahhhhh that makes sense! I'm missing some context about how this all works in production, so take this suggestion with a grain of salt :) Maybe that context about how this all is working could be put in the README for others stumbling upon this repo.

**Comment by sampoder** [comment]
In development the site is now static!
